MODEL:
  NUM_CLASSES: 43
  BOX_HEAD:
    PREDICTOR: 'SSDLiteBoxPredictor'
  BACKBONE:
    NAME: 'mobilenet_v2'
    OUT_CHANNELS: (96, 1280, 512, 256, 256, 64)
  PRIORS:
    FEATURE_MAPS: [20, 10, 5, 3, 2, 1]
    STRIDES: [16, 32, 64, 107, 160, 320]
    MIN_SIZES: [60, 105, 150, 195, 240, 285]
    MAX_SIZES: [105, 150, 195, 240, 285, 330]
    ASPECT_RATIOS: [[2, 3], [2, 3], [2, 3], [2, 3], [2, 3], [2, 3]]
    BOXES_PER_LOCATION: [6, 6, 6, 6, 6, 6]
INPUT:
  IMAGE_SIZE: 320
DATASETS:
  TRAIN: ("mahjong_trainval", )
  TEST: ("mahjong_test", )
DATA_LOADER:
  NUM_WORKERS: 4
SOLVER:
  MAX_ITER: 60000
  LR_STEPS: [10000, 20000, 40000]
  GAMMA: 0.1
  BATCH_SIZE: 16
  LR: 1e-2
TEST:
    BATCH_SIZE: 16

OUTPUT_DIR: 'outputs/mobilenet_v2_ssd320_mahjong'